name: "Validate Bicep code"

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  LOCATION: "eastus"
  RESOURCE_GROUP: "bicep-rg"

jobs:
  Lint-and-preview:
    name: "Lint-and-preview"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Manually install Azure CLI
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Bicep Lint
        run: az bicep build --file src/main.bicep

      - name: "What-If"
        run:  az deployment group what-if \
              --name whatif-${{ github.run_id }} \
              --template-file src/main.bicep \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --result-format ResourceIdOnly