name: "Validate Bicep code"

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  LOCATION: "eastus"
  RESOURCE_GROUP: "bicep-rg"

jobs:
  Lint-and-preview:
    name: "Lint-and-preview"
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate to Az CLI using OIDC
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        # Checks that all Bicep configuration files adhere to a canonical format
      - name: Bicep Lint
        uses: Azure/cli@v1
        with:
          inlineScript: az bicep build --file src/main.bicep

      # Preview changes
      - name: "What-If"
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az deployment group what-if \
              --name whatif-${{ github.run_id }} \
              --template-file src/main.bicep \
              --resource-group $RESOURCE_GROUP > whatif
